### DISCUSSION TITLE
MQTT Hubitat and Pool Heater

### DISCUSSION THREAD

**Discussion by markstubb** [aqualinkd/AqualinkD#170] [General]
Trying to figure out how to properly configure a heater via MQTT on hubitat.  If I set it up as a thermostat (at least via the https://github.com/xAPPO/MQTT app), there are tons of topics that aren't appropriate (ie cool/emergency heat, etc) but I'm not sure how to map values to the extremely simple ones that are there for the pool or spa heater. It's really just on/off and setpoint.  Do other folks just create a switch to turn on/off as well as an integer type setting to control the temp and that's it?  I think it'd be cooler to set it as a stat.

**Comment by sfeakes** [comment]
Have you tried to just leave the topics that are not relevant empty?
For HomeKit/bridge, hassio, domoticz that’s all you need to do.

**Reply by markstubb** [reply]
I have indeed - the only thing is it seems the plugin just reverts those null strings back to default.  I haven't tried to look at the app code as yet.  Going to start messing with it again now to see what I can force it to do.

**Reply by markstubb** [reply]
Just for relevance, this is the array of config items just for a thermostat

> heatingSetpoint_Cmd: aqualinkd/Spa_Heater/setpoint/set
supportedThermostatFanModes_MAP: [heating,pending cool,pending heat,vent economizer,idle,cooling,fan only]
origin: user
thermostatMode_Topic: aqualinkd/Spa_Heater/enabled
thermostatMode_MAP: [1,0,1,1,1]
thermostatFanMode_MAP: [on,circulate,auto]
temperature_Topic: aqualinkd/Temperature/Pool
heatingSetpoint_Topic: aqualinkd/Spa_Heater/setpoint
thermostatOperatingState_MAP: [heating,pending cool,pending heat,vent economizer,idle,cooling,fan only]
supportedThermostatModes_MAP: [on,circulate,auto]
thermostatSetpoint_MAP: [on,circulate,auto]
mqtt: enabled
coolingSetpoint_Cmd: aqualinkd/Spa_Heater/set
temperature_Cmd:
coolingSetpoint_Topic: aqualinkd/Spa_Heater/setpoint
supportedThermostatFanModes_Cmd:
thermostatOperatingState_Cmd:
supportedThermostatFanModes_Topic: none
thermostatFanMode_Cmd:
supportedThermostatModes_Topic: none
lastRunningMode: heat
thermostatSetpoint_Cmd:
thermostatMode_Cmd: aqualinkd/Spa_Heater/set
supportedThermostatModes_Cmd:
thermostatFanMode_Topic: none
thermostatOperatingState_Topic: aqualinkd/Spa_Heater
coolingSetpoint_MAP: [1,0]
thermostatSetpoint_Topic: aqualinkd/Temperature/Air
properties: measure-temperature,heating-setpoint,cooling-setpoint,thermostat-setpoint,mode,fanmode,state,modes,fanmodes

**Comment by sfeakes** [comment]
You are really going to have to talk to the XAPPO dev or look at the code to figure out exactly what’s needed.
Looking at the _MAP options that are supported, it seems it shouldn’t be that difficult.

**Reply by markstubb** [reply]
I did the 1,0 MAPs myself, the others map oddly and I feel like hubitat is doing something with the thermostat similar to a pid since it has a config item for hysteresis.  I will ping the dev in his thread and see what options there are.  I was hoping someone else had integrated aqualinkd via MQTT for more than just turning stuff on and off via switches and monitoring temp.  Even setting up freeze protect is sketchy

**Comment by sfeakes** [comment]
AqualinkD has been integrated with thermostats via MQTT to HassIO, Homebridge, Domoticz and many others. Thermostats are usually used for Salt Water Generator, Pool&Spa heaters and freeze protect.  It's simply a case of setting the MQTT endpoints for set temp and get temp, on and off. Then if supported by the hub, turning off the cool and fan options.

Examples are in the repo.  Here is one for HassIO

```
- platform: mqtt
    unique_id: aqualink_pool_heater
    name: Pool Heater
    modes:
      - "off"
      - "heat"
    send_if_off: true
    initial: 70
    power_command_topic: "aqualinkd/Pool_Heater/set"
    payload_on: "1"
    payload_off: "0"
    current_temperature_topic: "aqualinkd/Temperature/Pool"
    min_temp: 70
    max_temp: 90
    mode_command_topic: "aqualinkd/Pool_Heater/set"
    mode_state_topic: "aqualinkd/Pool_Heater/enabled"
    mode_state_template: >-
      {% set values1 = { '0':'off', '1':'heat'} %}
      {{ values1[value] if value in values1.keys() else 'off' }}
    temperature_command_topic: "aqualinkd/Pool_Heater/setpoint/set"
    temperature_state_topic: "aqualinkd/Pool_Heater/setpoint"
    temperature_state_template: "{{ value_json }}"
```
