### DISCUSSION TITLE
Using AqualinkD with OpenHAB

### DISCUSSION THREAD

**Discussion by ballle98** [aqualinkd/AqualinkD#189] [Show and tell]
OpenHAB can use the MQTT binding to control AqualinkD.  With https://myopenhab.org/ Openhab provides free integration with google and Alexa.  I was able to set it up so alexa control spa and pool as thermostats.

Follow https://www.openhab.org/docs/tutorial/things_advanced.html
	1. Create MQTT bridge
	2. Create Generic MQTT thing for aqualinkd
	3. Channels are not discovered so you have to configure them like so.

```
UID: mqtt:topic:broker:aqualinkd
label: aqualinkd
thingTypeUID: mqtt:topic
configuration: {}
bridgeUID: mqtt:broker:broker
channels:
  - id: Filter_Pump
    channelTypeUID: mqtt:switch
    label: Filter Pump
    description: ""
    configuration:
      commandTopic: aqualinkd/Filter_Pump/set
      stateTopic: aqualinkd/Filter_Pump
      off: "0"
      on: "1"
  - id: Spa_Mode
    channelTypeUID: mqtt:switch
    label: Spa Mode
    description: ""
    configuration:
      commandTopic: aqualinkd/Spa_Mode/set
      stateTopic: aqualinkd/Spa_Mode
      off: "0"
      on: "1"
  - id: Aux_1
    channelTypeUID: mqtt:switch
    label: Cleaner
    description: ""
    configuration:
      commandTopic: aqualinkd/Aux_1/set
      stateTopic: aqualinkd/Aux_1
      off: "0"
      on: "1"
  - id: Aux_4
    channelTypeUID: mqtt:switch
    label: Pool Light
    description: ""
    configuration:
      commandTopic: aqualinkd/Aux_4/set
      stateTopic: aqualinkd/Aux_4
      off: "0"
      on: "1"
  - id: Aux_5
    channelTypeUID: mqtt:switch
    label: Spa Light
    description: ""
    configuration:
      commandTopic: aqualinkd/Aux_5/set
      stateTopic: aqualinkd/Aux_5
      off: "0"
      on: "1"
  - id: Freeze_Protect
    channelTypeUID: mqtt:switch
    label: Freeze Protect
    description: ""
    configuration:
      stateTopic: aqualinkd/Freeze_Protect/enabeled
      off: "0"
      on: "1"
  - id: Pool_Heater
    channelTypeUID: mqtt:switch
    label: Pool Heater
    description: ""
    configuration:
      commandTopic: aqualinkd/Pool_Heater/set
      stateTopic: aqualinkd/Pool_Heater/enabled
      off: "0"
      on: "1"
  - id: Spa_Heater
    channelTypeUID: mqtt:switch
    label: Spa Heater
    description: null
    configuration:
      commandTopic: aqualinkd/Spa_Heater/set
      stateTopic: aqualinkd/Spa_Heater/enabled
      off: "0"
      on: "1"
  - id: Temperature_Air
    channelTypeUID: mqtt:number
    label: Air Temperature
    description: ""
    configuration:
      stateTopic: aqualinkd/Temperature/Air
      unit: F
  - id: Temperature_Pool
    channelTypeUID: mqtt:number
    label: Pool Temperature
    description: null
    configuration:
      stateTopic: aqualinkd/Temperature/Pool
      unit: F
  - id: Temperature_Spa
    channelTypeUID: mqtt:number
    label: Spa Temperature
    description: null
    configuration:
      stateTopic: aqualinkd/Temperature/Spa
      unit: F
  - id: Pool_Heater_setpoint
    channelTypeUID: mqtt:number
    label: Pool Heater setpoint
    description: ""
    configuration:
      commandTopic: aqualinkd/Pool_Heater/setpoint/set
      unit: F
      min: 36
      stateTopic: aqualinkd/Pool_Heater/setpoint
      max: 104
  - id: Spa_Heater_setpoint
    channelTypeUID: mqtt:number
    label: Spa Heater setpoint
    description: null
    configuration:
      commandTopic: aqualinkd/Spa_Heater/setpoint/set
      unit: F
      min: 36
      stateTopic: aqualinkd/Spa_Heater/setpoint
      max: 104
  - id: Freeze_Protect_setpoint
    channelTypeUID: mqtt:number
    label: Freeze Protect setpoint
    description: null
    configuration:
      commandTopic: aqualinkd/Freeze_Protect/setpoint/set
      unit: F
      min: 34
      stateTopic: aqualinkd/Freeze_Protect/setpoint
      max: 42
  - id: Freexe_Protect_active
    channelTypeUID: mqtt:switch
    label: Freexe Protect active
    description: null
    configuration:
      stateTopic: aqualinkd/Freexe_Protect
      off: "0"
      on: "1"
  - id: Pool_Heater_active
    channelTypeUID: mqtt:switch
    label: Pool Heater active
    description: null
    configuration:
      stateTopic: aqualinkd/Pool_Heater
      off: "0"
      on: "1"
  - id: Spa_Heater_active
    channelTypeUID: mqtt:switch
    label: Spa Heater active
    description: null
    configuration:
      stateTopic: aqualinkd/Spa_Heater
      off: "0"
      on: "1"

```

Reference 

https://community.openhab.org/t/aqualinkd-mqtt-to-control-the-pool/124145
https://community.openhab.org/t/alexa-thermostat-will-not-allow-setpoint-greater-than-99-f/124965
