### ISSUE TITLE
Duplicate sensors in Home Assistant

### ISSUE THREAD

**Issue by johntdyer** [aqualinkd/AqualinkD#437]
Noticed I have a few duplicate sensors in Home Assistant via MQTT.  Some of them have a device attribute but most do not. 

<img width="1411" alt="Image" src="https://github.com/user-attachments/assets/716cbc2c-79f7-4bfe-915d-b317cb386fa5" />

a cursory glance seems to show that both sensors have the updated value, I am just unsure why they exists and why they dont all have a parent device ? 

Home Assistant: 2025.06
Aqalinkd 2.6.3

**Comment by johntdyer** [comment]
Noticed I am a few versions behind, upgrading and will post an update in a moment

**Comment by johntdyer** [comment]
seems like this was because I was using the old method of defining the mqtt sensors that predates the auto discovery features

```
mqtt:
  climate:
    - unique_id: aqualinkd_pool_heater
      name: AqualinkD Pool Heater
      modes:
        - "off"
        - "heat"
      # # send_if_off: true
      initial: 70
      # power_command_topic: "aqualinkd/Pool_Heater/set"
      payload_on: "1"
      payload_off: "0"
      current_temperature_topic: "aqualinkd/Temperature/Pool"
      min_temp: 70
      max_temp: 90
      mode_command_topic: "aqualinkd/Pool_Heater/set"
      mode_state_topic: "aqualinkd/Pool_Heater/enabled"
      mode_state_template: >-
        {% set values1 = { '0':'off', '1':'heat'} %}
        {{ values1[value] if value in values1.keys() else 'off' }}
      temperature_command_topic: "aqualinkd/Pool_Heater/setpoint/set"
      temperature_state_topic: "aqualinkd/Pool_Heater/setpoint"
      temperature_state_template: "{{ value_json }}"

    - unique_id: aqualinkd_spa_heater
      name: AqualinkD Spa Heater
      modes:
        - "off"
        - "heat"
      # send_if_off: true
      initial: 100
      # power_command_topic: "aqualinkd/Spa_Heater/set"
      payload_on: "1"
      payload_off: "0"
      current_temperature_topic: "aqualinkd/Temperature/Spa"
      min_temp: 80
      max_temp: 104
      mode_command_topic: "aqualinkd/Spa_Heater/set"
      mode_state_topic: "aqualinkd/Spa_Heater/enabled"
      mode_state_template: >-
        {% set values2 = { '0':'off', '1':'heat'} %}
        {{ values2[value] if value in values2.keys() else 'off' }}
      temperature_command_topic: "aqualinkd/Spa_Heater/setpoint/set"
      temperature_state_topic: "aqualinkd/Spa_Heater/setpoint"
      temperature_state_template: "{{ value_json }}"

    - unique_id: aqualinkd_freeze_protect
      name: AqualinkD Freeze Protect
      modes:
        - "off"
        - "cool"
      # send_if_off: true
      initial: 36
      # power_command_topic: "aqualinkd/Freeze_Protect/set"
      payload_on: "1"
      payload_off: "0"
      current_temperature_topic: "aqualinkd/Temperature/Air"
      min_temp: 34
      max_temp: 42
      mode_command_topic: "aqualinkd/Freeze_Protect/set"
      mode_state_topic: "aqualinkd/Freeze_Protect/enabled"
      mode_state_template: >-
        {% set values = { '0':'off', '1':'cool'} %}
        {{ values[value] if value in values.keys() else 'off' }}
      temperature_command_topic: "aqualinkd/Freeze_Protect/setpoint/set"
      temperature_state_topic: "aqualinkd/Freeze_Protect/setpoint"
      temperature_state_template: "{{ value_json }}"

  #----AQUALINK SWITCHES

  switch:
    - unique_id: aqualinkd_freeze_protect
      name: "AqualinkD Freeze Protection"
      state_topic: "aqualinkd/Freeze_Protect/enabled"
      command_topic: "aqualinkd/Freeze_Protect/set" #NOTE: aqualinkd does not support toggling Freeze Protect due to being a menu option rather than a simple command. Use your RS controller to change the setting. This should be configured as a binary_sensor instead of a switch to make it more obvious but I kept it a switch in case the limitation changes in the future.
      json_attributes_topic: "aqualinkd/Freeze_Protect"
      json_attributes_template: "{{ {'active': value|int} | tojson }}"
      qos: 1
      payload_on: "1"
      payload_off: "0"
      retain: false
      icon: mdi:snowflake

    - unique_id: aqualinkd_filter_pump
      name: "AqualinkD Filter Pump"
      state_topic: "aqualinkd/Filter_Pump"
      command_topic: "aqualinkd/Filter_Pump/set"
      json_attributes_topic: "aqualinkd/Filter_Pump/delay"
      json_attributes_template: "{{ {'delay': value|int} | tojson }}"
      qos: 1
      payload_on: "1"
      payload_off: "0"
      retain: false

    - unique_id: aqualinkd_spa_mode
      name: "AqualinkD Spa Mode"
      state_topic: "aqualinkd/Spa_Mode"
      command_topic: "aqualinkd/Spa_Mode/set"
      json_attributes_topic: "aqualinkd/Spa_Mode/delay"
      json_attributes_template: "{{ {'delay': value|int} | tojson }}"
      qos: 1
      payload_on: "1"
      payload_off: "0"
      retain: false
      icon: mdi:hot-tub

    - unique_id: aqualinkd_water_falls
      name: "AqualinkD Waterfalls"
      state_topic: "aqualinkd/Aux_1"
      command_topic: "aqualinkd/Aux_1/set"
      json_attributes_topic: "aqualinkd/Aux_1/delay"
      json_attributes_template: "{{ {'delay': value|int} | tojson }}"
      qos: 1
      payload_on: "1"
      payload_off: "0"
      retain: false
      icon: fas:fa-water

    - unique_id: aqualinkd_spa_blower
      name: "AqualinkD Spa Blower"
      state_topic: "aqualinkd/Aux_2"
      command_topic: "aqualinkd/Aux_2/set"
      json_attributes_topic: "aqualinkd/Aux_2/delay"
      json_attributes_template: "{{ {'delay': value|int} | tojson }}"
      qos: 1
      payload_on: "1"
      payload_off: "0"
      retain: false
      icon: mdi:fan

    - unique_id: aqualinkd_pool_light
      name: "AqualinkD Pool Lights"
      state_topic: "aqualinkd/Aux_3"
      command_topic: "aqualinkd/Aux_3/set"
      json_attributes_topic: "aqualinkd/Aux_3/delay"
      json_attributes_template: "{{ {'delay': value|int} | tojson }}"
      qos: 1
      payload_on: "1"
      payload_off: "0"
      retain: false
      icon: mdi:lightbulb

    - unique_id: aqualinkd_pool_solar_heater
      name: "AqualinkD Solar Heater"
      state_topic: "aqualinkd/Solar_Heater"
      command_topic: "aqualinkd/Solar_Heater/set"
      json_attributes_topic: "aqualinkd/Solar_Heater/delay"
      json_attributes_template: "{{ {'delay': value|int} | tojson }}"
      qos: 1
      payload_on: "1"
      payload_off: "0"
      retain: false
      icon: mdi:lightbulb

    - unique_id: aqualinkd_pool_heater
      name: "AqualinkD Pool Heater"
      state_topic: "aqualinkd/Pool_Heater/enabled"
      command_topic: "aqualinkd/Pool_Heater/set"
      json_attributes_topic: "aqualinkd/Pool_Heater"
      json_attributes_template: "{{ {'active': value|int} | tojson }}"
      qos: 1
      payload_on: "1"
      payload_off: "0"
      retain: false
      icon: mdi:fire

    - unique_id: aqualinkd_spa_heater
      name: "AqualinkD Spa Heater"
      state_topic: "aqualinkd/Spa_Heater/enabled"
      command_topic: "aqualinkd/Spa_Heater/set"
      json_attributes_topic: "aqualinkd/Spa_Heater"
      json_attributes_template: "{{ {'active': value|int} | tojson }}"
      qos: 1
      payload_on: "1"
      payload_off: "0"
      retain: false
      icon: mdi:fire

  #----AQUALINK BINARY SENSORS
  binary_sensor:
    - unique_id: aqualinkd_pool_heater
      state_topic: "aqualinkd/Pool_Heater"
      name: "AqualinkD Pool Heating"
      qos: 0
      payload_on: "1"
      payload_off: "0"

    - unique_id: aqualinkd_spa_heater
      state_topic: "aqualinkd/Spa_Heater"
      name: "AqualinkD Spa Heating"
      qos: 0
      payload_on: "1"
      payload_off: "0"

    - unique_id: aqualinkd_freeze_protection
      state_topic: "aqualinkd/Freeze_Protect"
      name: "AqualinkD Freeze Protecting"
      qos: 0
      payload_on: "1"
      payload_off: "0"

    - unique_id: aqualinkdd_alive
      state_topic: "aqualinkd/Alive"
      name: "AqualinkD Alive"
      qos: 0
      payload_on: "1"
      payload_off: "0"

    - unique_id: aqualinkdd_battery
      state_topic: "aqualinkd/Battery"
      name: "AqualinkD Battery"
      qos: 0
      payload_on: "0"
      payload_off: "1"
      device_class: battery

    - unique_id: aqualinkdd_filter_pump_delay
      state_topic: "aqualinkd/Filter_Pump/delay"
      name: "AqualinkD Filter Pump Delay"
      qos: 0
      payload_on: "1"
      payload_off: "0"

    - unique_id: aqualinkdd_spa_mode_delay
      state_topic: "aqualinkd/Spa_Mode/delay"
      name: "AqualinkD Spa Mode Delay"
      qos: 0
      payload_on: "1"
      payload_off: "0"

    - unique_id: aqualinkdd_pool_light_delay
      state_topic: "aqualinkd/Solar_Heater/delay"
      name: "AqualinkD Pool Light Delay"
      qos: 0
      payload_on: "1"
      payload_off: "0"

    - unique_id: aqualinkdd_cleaner_delay
      state_topic: "aqualinkd/Aux_1/delay"
      name: "AqualinkD Cleaner Delay"
      qos: 0
      payload_on: "1"
      payload_off: "0"

    - unique_id: aqualinkdd_spa_blower_delay
      state_topic: "aqualinkd/Aux_2/delay"
      name: "AqualinkD Spa Blower Delay"
      qos: 0
      payload_on: "1"
      payload_off: "0"

    - unique_id: aqualinkdd_spa_light_delay
      state_topic: "aqualinkd/Aux_3/delay"
      name: "AqualinkD Spa Light Delay"
      qos: 0
      payload_on: "1"
      payload_off: "0"

  #----AQUALINK SENSORS

  sensor:
    - unique_id: aqualinkd_pool_state
      state_topic: "aqualinkd/Service_Mode"
      name: "AqualinkD Mode"
      value_template: "{{ value }}"
      icon: mdi:wrench

    - unique_id: aqualinkd_message
      state_topic: "aqualinkd/Display_Message"
      name: "AqualinkD Display Message"
      value_template: "{{ value }}"
      icon: mdi:message

    - unique_id: aqualinkd_air_temp
      state_topic: "aqualinkd/Temperature/Air"
      name: "AqualinkD Air Temp"
      value_template: >-
        {% if value_json is defined %}
        {{ "%.2f"|format(value_json|float) }}
        {% else %}
          0.0
        {% endif %}
      unit_of_measurement: "°C"
      device_class: temperature

    - unique_id: aqualinkd_spa_temp
      state_topic: "aqualinkd/Temperature/Spa"
      name: "AqualinkD Spa Temp"
      value_template: >-
        {% if value_json is defined %}
        {{ "%.2f"|format(value_json|float) }}
        {% else %}
          0.0
        {% endif %}
      unit_of_measurement: "°C"
      device_class: temperature

      # expire_after: 30
    - unique_id: aqualinkd_pool_temp
      state_topic: "aqualinkd/Temperature/Pool"
      name: "AqualinkD Pool Temp"
      value_template: >-
        {% if value_json is defined %}
        {{ "%.2f"|format(value_json|float) }}
        {% else %}
          0.0
        {% endif %}

      # {{ value_json }}
      unit_of_measurement: "°C"
      # expire_after: 30
      device_class: temperature

    - unique_id: aqualinkd_pool_heater_temp
      state_topic: "aqualinkd/Pool_Heater/setpoint"
      name: "AqualinkD Pool Heater Temp"
      value_template: >-
        {% if value_json is defined %}
        {{ "%.2f"|format(value_json|float) }}
        {% else %}
          0.0
        {% endif %}
      unit_of_measurement: "°C"
      device_class: temperature

    - unique_id: aqualinkd_spa_heater_temp
      state_topic: "aqualinkd/Spa_Heater/setpoint"
      name: "AqualinkD Spa Heater Temp"
      value_template: >-
        {% if value_json is defined %}
        {{ "%.2f"|format(value_json|float) }}
        {% else %}
          0.0
        {% endif %}
      unit_of_measurement: "°C"
      device_class: temperature
```

Removed this and things seem happier
